// <auto-generated />
using System;
using Benistar.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Benistar.Api.Migrations
{
    [DbContext(typeof(BenefitsDbContext))]
    [Migration("20260129035447_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Benistar.Shared.Benefit", b =>
                {
                    b.Property<int>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitId"));

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenefitType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyPremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProviderName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BenefitId");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            BenefitId = 1,
                            BenefitName = "Medicare Supplement Plan F",
                            BenefitType = "Medical",
                            IsActive = true,
                            MonthlyPremium = 185.50m,
                            ProviderName = "Blue Cross Blue Shield"
                        },
                        new
                        {
                            BenefitId = 2,
                            BenefitName = "Medicare Advantage HMO",
                            BenefitType = "Medical",
                            IsActive = true,
                            MonthlyPremium = 0.00m,
                            ProviderName = "UnitedHealthcare"
                        },
                        new
                        {
                            BenefitId = 3,
                            BenefitName = "Dental PPO",
                            BenefitType = "Dental",
                            IsActive = true,
                            MonthlyPremium = 45.00m,
                            ProviderName = "Delta Dental"
                        },
                        new
                        {
                            BenefitId = 4,
                            BenefitName = "Vision Plan",
                            BenefitType = "Vision",
                            IsActive = true,
                            MonthlyPremium = 18.75m,
                            ProviderName = "VSP"
                        },
                        new
                        {
                            BenefitId = 5,
                            BenefitName = "Prescription Drug Plan",
                            BenefitType = "Pharmacy",
                            IsActive = true,
                            MonthlyPremium = 32.50m,
                            ProviderName = "CVS Caremark"
                        });
                });

            modelBuilder.Entity("Benistar.Shared.Retiree", b =>
                {
                    b.Property<int>("RetireeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RetireeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetireeId");

                    b.ToTable("Retirees");

                    b.HasData(
                        new
                        {
                            RetireeId = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1955, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anurag.varma@benistar.com",
                            FirstName = "Anurag",
                            IsActive = true,
                            LastName = "Varma"
                        },
                        new
                        {
                            RetireeId = 2,
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1958, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mark.johnson@benistar.com",
                            FirstName = "Mark",
                            IsActive = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            RetireeId = 3,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1953, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.williams@benistar.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Williams"
                        },
                        new
                        {
                            RetireeId = 4,
                            CreatedAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1960, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patricia.brown@benistar.com",
                            FirstName = "Patricia",
                            IsActive = true,
                            LastName = "Brown"
                        });
                });

            modelBuilder.Entity("Benistar.Shared.RetireeBenefit", b =>
                {
                    b.Property<int>("RetireeBenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RetireeBenefitId"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CoverageEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CoverageStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RetireeId")
                        .HasColumnType("int");

                    b.HasKey("RetireeBenefitId");

                    b.HasIndex("BenefitId");

                    b.HasIndex("RetireeId");

                    b.ToTable("RetireeBenefits");

                    b.HasData(
                        new
                        {
                            RetireeBenefitId = 1,
                            BenefitId = 1,
                            CoverageStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 1
                        },
                        new
                        {
                            RetireeBenefitId = 2,
                            BenefitId = 3,
                            CoverageStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 1
                        },
                        new
                        {
                            RetireeBenefitId = 3,
                            BenefitId = 2,
                            CoverageStartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 2
                        },
                        new
                        {
                            RetireeBenefitId = 4,
                            BenefitId = 4,
                            CoverageStartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 2
                        },
                        new
                        {
                            RetireeBenefitId = 5,
                            BenefitId = 1,
                            CoverageStartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 3
                        },
                        new
                        {
                            RetireeBenefitId = 6,
                            BenefitId = 5,
                            CoverageStartDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 3
                        },
                        new
                        {
                            RetireeBenefitId = 7,
                            BenefitId = 2,
                            CoverageStartDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrolledAt = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RetireeId = 4
                        });
                });

            modelBuilder.Entity("Benistar.Shared.RetireeBenefit", b =>
                {
                    b.HasOne("Benistar.Shared.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Benistar.Shared.Retiree", "Retiree")
                        .WithMany("RetireeBenefits")
                        .HasForeignKey("RetireeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benefit");

                    b.Navigation("Retiree");
                });

            modelBuilder.Entity("Benistar.Shared.Retiree", b =>
                {
                    b.Navigation("RetireeBenefits");
                });
#pragma warning restore 612, 618
        }
    }
}
